version: 2

updates:
- package-ecosystem: bundler
  directory: "/"
  insecure-external-code-execution: allow
  schedule:
    interval: daily
    timezone: America/New_York
  open-pull-requests-limit: 5
  assignees:
  - nicreed
  labels:
  - dependencies
