=begin
#Credit Card API v1

#Credit Card API for authorizing and charging credit cards.

OpenAPI spec version: 1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for CreditCardRestClient::StatusApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'StatusApi' do
  before do
    # run before each test
    @instance = CreditCardRestClient::StatusApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of StatusApi' do
    it 'should create an instance of StatusApi' do
      expect(@instance).to be_instance_of(CreditCardRestClient::StatusApi)
    end
  end

  # unit tests for external_status_check
  # Check external API status
  # Authenticates given credentials and reports external API status
  # @param [Hash] opts the optional parameters
  # @option opts [ExternalStatusRequest] :request 
  # @return [ExternalStatusResponse]
  describe 'external_status_check test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for status_check
  # API status check
  # Checks to see if the API can return the current system time
  # @param [Hash] opts the optional parameters
  # @return [StatusResponse]
  describe 'status_check test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
