=begin
#Credit Card API v1

#Credit Card API for authorizing and charging credit cards.

OpenAPI spec version: 1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

# Common files
require 'credit_card_rest_client/api_client'
require 'credit_card_rest_client/api_error'
require 'credit_card_rest_client/version'
require 'credit_card_rest_client/configuration'

# Models
require 'credit_card_rest_client/models/charge_details'
require 'credit_card_rest_client/models/charge_result'
require 'credit_card_rest_client/models/external_status_request'
require 'credit_card_rest_client/models/external_status_response'
require 'credit_card_rest_client/models/status_response'

# APIs
require 'credit_card_rest_client/api/authorize_api'
require 'credit_card_rest_client/api/charge_api'
require 'credit_card_rest_client/api/status_api'

module CreditCardRestClient
  class << self
    # Customize default settings for the SDK using block.
    #   CreditCardRestClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
